# frontend service for quantum1
apiVersion: v1
kind: Service
metadata:
  name: quantum1-frontend-service
spec:
  selector:
    app: quantum1-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

