apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-egress-https-and-dns
  namespace: quantum1space
spec:
  podSelector:
    matchLabels:
      app: quantum1-backend
  policyTypes:
    - Egress
  egress:
    # Allow all outbound traffic (simplified approach)
    - to: []
