#quantum1_k8s.yaml
# This file contains the Kubernetes configuration for deploying the Quantum1 application in IBM Cloud Kubernetes cluster.
apiVersion: v1
kind: Secret
metadata:
  name: quantum1-secrets
  namespace: default
stringData:
  IBM_QUANTUM_API_TOKEN: "<paste-your-quantum-token-here>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum1
  template:
    metadata:
      labels:
        app: quantum1
    spec:
      containers:
      - name: quantum1
        image: us.icr.io/accelcq/quantum1:latest
        ports:
        - containerPort: 8000
        env:
        - name: IBM_QUANTUM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: quantum1-secrets
              key: IBM_QUANTUM_API_TOKEN
        volumeMounts:
        - mountPath: /app/execution_log.log
          name: log-volume
          subPath: execution_log.log
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: quantum1-log-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum1-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quantum1-service
spec:
  type: LoadBalancer
  selector:
    app: quantum1
  ports:
    - port: 80
      targetPort: 8000
