#quantum1_k8s.yaml
# This file contains the Kubernetes configuration for deploying the Quantum1 application in IBM Cloud Kubernetes cluster.
apiVersion: v1
kind: Secret
metadata:
  name: quantum1-secrets
  namespace: quantum1space
type: Opaque
stringData:
  IBM_QUANTUM_API_TOKEN: "${IBM_QUANTUM_API_TOKEN}"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum1-log-pvc
  namespace: quantum1space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum1-deployment
  namespace: quantum1space
  labels:
    app: quantum1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum1
  template:
    metadata:
      labels:
        app: quantum1
    spec:
      containers:
        - name: quantum1
          image: us.icr.io/quantum1space/quantum1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: IBM_QUANTUM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: quantum1-secrets
                  key: IBM_QUANTUM_API_TOKEN
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
              subPath: execution_log.log
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: quantum1-log-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum1-frontend
  namespace: quantum1space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum1-frontend
  template:
    metadata:
      labels:
        app: quantum1-frontend
    spec:
      containers:
      - name: quantum1-frontend
        image: us.icr.io/quantum1space/quantum1-frontend:latest
        ports:
        - containerPort: 80
        env:
          - name: QUANTUM1_API_URL
            value: "http://quantum1-service.quantum1space.svc.cluster.local:8080"
        volumeMounts:
          - name: log-volume
            mountPath: /app/logs
            subPath: execution_log.log
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: quantum1-log-pvc
            readOnly: false
---

apiVersion: v1
kind: Service
metadata:
  name: quantum1-service

spec:
  selector:
    app: quantum1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quantum1-frontend-service
  namespace: quantum1space
spec:
  selector:
    app: quantum1-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
