#quantum1_k8s.yaml
# This file contains the Kubernetes configuration for deploying the Quantum1 application in IBM Cloud Kubernetes cluster.
apiVersion: v1
kind: Secret
metadata:
  name: quantum1-secrets
  namespace: accelcqnamespace
type: Opaque
stringData:
  IBM_QUANTUM_API_TOKEN: "${IBM_QUANTUM_API_TOKEN}"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantum1-log-pvc
  namespace: accelcqnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum1-deployment
  namespace: accelcqnamespace
  labels:
    app: quantum1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum1
  template:
    metadata:
      labels:
        app: quantum1
    spec:
      containers:
        - name: quantum1
          image: us.icr.io/accelcqnamespace/quantum1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: IBM_QUANTUM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: quantum1-secrets
                  key: IBM_QUANTUM_API_TOKEN
          volumeMounts:
            - name: log-volume
              mountPath: /app/execution_log.log
              subPath: execution_log.log
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: quantum1-log-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: quantum1-service
  namespace: accelcqnamespace
spec:
  selector:
    app: quantum1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
